src/PublicWebSite/Controllers/NewsController.cs
using PagedList;
using PublicWebSite.DAL;
using PublicWebSite.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace PublicWebSite.Controllers
{
    [Authorize(Roles = "Admin")]
    public partial class NewsController : Controller
    {
        private MainContext db = new MainContext();

        // GET: /News/
        public virtual ActionResult Index(string sortOrder, int? page)
        {


           

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var lstNews = from s in db.Newses
                           select s;
            switch (sortOrder)
            {
                case "name_desc":
                    lstNews = lstNews.OrderByDescending(s => s.Title);
                    break;
                case "Date":
                    lstNews = lstNews.OrderByDescending(s => s.InsertDate);
                    break;
                case "date_desc":
                    lstNews = lstNews.OrderBy(s => s.Title);
                    break;
                default:
                    lstNews = lstNews.OrderBy(s => s.Title);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(lstNews.ToPagedList(pageNumber, pageSize));

        }

        // GET: /News/Details/5
        public virtual ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.Newses.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // GET: /News/Create
        public virtual ActionResult Create()
        {
            return View();
        }

        // POST: /News/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Create([Bind(Include = "Id,Title,Body,KeyWords,InsertDate,UpdateDate,IsDeleted,DeleteDate,IsActive,ActiveDeActiveDate")] News news)
        {
            if (ModelState.IsValid)
            {
                db.Newses.Add(news);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(news);
        }

        // GET: /News/Edit/5
        public virtual ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.Newses.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: /News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Edit([Bind(Include = "Id,Title,Body,KeyWords,InsertDate,UpdateDate,IsDeleted,DeleteDate,IsActive,ActiveDeActiveDate")] News news)
        {
            if (ModelState.IsValid)
            {
                db.Entry(news).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(news);
        }

        // GET: /News/Delete/5
        public virtual ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            News news = db.Newses.Find(id);
            if (news == null)
            {
                return HttpNotFound();
            }
            return View(news);
        }

        // POST: /News/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public virtual ActionResult DeleteConfirmed(int id)
        {
            News news = db.Newses.Find(id);
            db.Newses.Remove(news);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/PublicWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - @PublicWebSite.Resources.Common.ControlPanelTitle</title>

    @Styles.Render("~/Content/css")
  @Scripts.Render("~/bundles/modernizr")

    </head>

<body style="background-image:url(../../Content/Images/bg.png); background-repeat:repeat">

    <nav class="navbar navbar-inverse" role="navigation" style="font-size:smaller">
        <ul class="nav navbar-nav pull-right">
            <li>@Html.ActionLink(@PublicWebSite.Resources.Common.BackToMainPage, "Index", "Main")</li>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">تنظیمات محتوا <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">

                    <li>@Html.ActionLink(@PublicWebSite.Resources.Common.Heme, "MainPage", "Home")</li>
                    <li>@Html.ActionLink(@PublicWebSite.Resources.Common.AboutUs, "About", "Home")</li>
                    <li>@Html.ActionLink(@PublicWebSite.Resources.Common.ContactUs, "Contact", "Home")</li>
                    <li>@Html.ActionLink(@PublicWebSite.Resources.Common.Factors, "Index", "SystemConstant")</li>
                    <li>@Html.ActionLink(@PublicWebSite.Resources.Common.LinList, "Index", "LinkList")</li>

                </ul>
            </li>

            <li>@Html.ActionLink(@PublicWebSite.Resources.Common.Articles, "Index", "Articles")</li>
            <li>@Html.ActionLink(@PublicWebSite.Resources.Common.ElectronicBill.ToString(), "Index", "UsersPayment")</li>
            <li>@Html.ActionLink(@PublicWebSite.Resources.Common.Messages, "Index", "Message")</li>
            <li>@Html.ActionLink(@PublicWebSite.Resources.Common.News, "Index", "News")</li>
            <li>@Html.ActionLink(@PublicWebSite.Resources.Common.UsersList.ToString(), "Index", "users")</li>
            <li>@Html.ActionLink(@PublicWebSite.Resources.Common.ContactUsList, "Index", "ContactUsList")</li>
            <li>@Html.ActionLink("خانه", "Index", "Home") </li>

        </ul>

    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - @PublicWebSite.Resources.Common.ControlPanelTitle</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

src/PublicWebSite/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/kendo/css")


</head>
<body style="background-image:url(../../Content/Images/bg.png); background-repeat:repeat">

    <div class="container" style="align-content:center ;width:1000px;">

        <img src="~/Content/Images/tt.png" style="border-radius: 10px 10px 0px;align-self:center " />


        <div class="navbar" role="navigation" style="width:1000px;border-radius:0px 0px 20px 20px;background-image:url(../../Content/Images/men.png);background-repeat:repeat">


            <ul class="nav nav-pills pull-right " style="font-size:smaller">

                <li class="btn-warning btn-sm" style="text-emphasis-color:brown ; border-radius:5px"><a style="color:black " href="~/Main/AboutUs"> @PublicWebSite.Resources.Common.AboutUs </a> </li>
                <li class="btn-warning btn-sm" style="text-emphasis-color:brown ; border-radius:5px"><a style="color:black " href="~/Main/ContactUs"> @PublicWebSite.Resources.Common.ContactUs </a> </li>


                @Html.Action("LoadArticles", "Partials")

                <li class="btn-warning btn-sm" style="text-emphasis-color:brown ; border-radius:5px"><a style="color:black " href="~/Main/News"> @PublicWebSite.Resources.Common.News </a> </li>
                <li class="btn-warning btn-sm" style="text-emphasis-color:brown ; border-radius:5px"><a style="color:black " href="~/Main/Index"> @PublicWebSite.Resources.Common.Heme </a> </li>

            </ul>

        </div>


        <div class="row">

            <div class="container body-content" style="width:1000px">

                <div style="width:1000px;align-items:center">

                    <div style="width:220px;float:left;margin-right:5px">@Html.Action("LoadNews", "Partials") <br /> @Html.Action("LoadLinks", "Partials")</div>

                    <div style="width:600px;float:left ;margin-right:5px">@RenderBody()</div>

                    <div style="width:170px">@Html.Action("LogOnPartial", "Partials") </div>

                </div>
            </div>
        </div>
        <div class="row">
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - @PublicWebSite.Resources.Common.MainPageFooter</p>
            </footer>

        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>

src/PublicWebSite/Views/Shared/_LoadArticles.cshtml
@model IEnumerable<PublicWebSite.Models.ContentPage>
<li class="dropdown btn-warning btn-sm">
    <a style="color:black" href="#" class="dropdown-toggle" data-toggle="dropdown">@PublicWebSite.Resources.Common.Articles <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">

        @foreach (var item in Model)
        {
            <li><a href="~/Main/ReadArticle/@item.Id">@item.Title</a></li>
        }
    </ul>
</li>

src/PublicWebSite/Views/Shared/_LoadLinks.cshtml
@model IEnumerable<PublicWebSite.Models.Link>
<div class="panel panel-success" style="direction: rtl; width:100%;">
    <div class="panel-heading" style="text-align: center">@PublicWebSite.Resources.Common.UsefulLinks</div>
    <div class="panel-body">
        @foreach (var item in Model)
        {
            <div style="text-align:right">

                <img src="~/Content/Images/Link.png" width="30px" height="30px" />
                <a href=@item.LinkAddress>@item.Title</a>
                <hr>
            </div>
        }
    </div>

</div>

src/PublicWebSite/Views/Shared/_LoadNews.cshtml
@model IEnumerable<PublicWebSite.Models.News>
<div class="panel panel-primary" style="direction: rtl; width: 100%;">
    <div class="panel-heading" style="text-align: center">آخرین اخبار</div>
    <div class="panel-body" >
        @foreach (var item in Model)
{
    <div style="text-align:right">
        
        <img src="~/Content/Images/News.png"  width="30px" height="30px"/>
        <a href="~/Main/ReadNews/@item.Id">@item.Title</a>   
        <hr>
    </div>
}
    </div>

</div>

src/PublicWebSite/Views/Shared/_PageContent.cshtml
@model PublicWebSite.Models.ContentPage
<p>
    @Html.Raw( Model.Body)
</p>