src/PublicWebSite/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PublicWebSite.Utility;

namespace PublicWebSite.Controllers
{
    public class FileController : Controller
    {
        public virtual ActionResult Index(PublicWebSite.Models.Message s)
        {
            PublicWebSite.Models.Message n=new  PublicWebSite.Models.Message();
            ViewBag.message  =s;
            return View(n);
        }

        /// <summary>
        /// Uploads the file.
        /// </summary>
        /// <returns></returns>

        [HttpPost]
        public ContentResult UploadFiles()
        {

            var r = new List<UploadFilesResult>();

            foreach (string file in Request.Files)
            {
                HttpPostedFileBase hpf = Request.Files[file] as HttpPostedFileBase;
                if (hpf.ContentLength == 0)
                    continue;

                string savedFileName = Path.Combine(Server.MapPath("~/MessageAttach"), Path.GetFileName(hpf.FileName));
                hpf.SaveAs(savedFileName);

                r.Add(new UploadFilesResult()
                {
                    Name = hpf.FileName,
                    Length = hpf.ContentLength,
                    Type = hpf.ContentType
                });
            }
            return Content("{\"name\":\"" + r[0].Name + "\",\"type\":\"" + r[0].Type + "\",\"size\":\"" + string.Format("{0} bytes", r[0].Length) + "\"}", "application/json");
        }

    }
}

src/PublicWebSite/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PublicWebSite.Models;
using PublicWebSite.DAL;
using System.Media;
using System.Web.Util;
using System.IO;
using PublicWebSite.Utility;

namespace PublicWebSite.Controllers
{
    [Authorize(Roles = "Admin")]
    public partial class MessageController : Controller
    {
        private MainContext db = new MainContext();

        // GET: /Message/
        public virtual ActionResult Index(string sortOrder, int? page, int? idi)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            
            UserInfo model = new UserInfo();

            model = db.UserInfos.Where(c => c.UserName == User.Identity.Name).FirstOrDefault();


            var lstMessages = from s in db.Messages
                              where s.user_id == model.Id
                             select s;

            switch (sortOrder)
            {
                case "name_desc":
                    lstMessages = lstMessages.OrderByDescending(s => s.Title);
                    break;
                case "Date":
                    lstMessages = lstMessages.OrderByDescending(s => s.InsertDate);
                    break;
                case "date_desc":
                    lstMessages = lstMessages.OrderBy(s => s.Title);
                    break;
                default:
                    lstMessages = lstMessages.OrderBy(s => s.Title);
                    break;
            }
            const int pageSize = 10;
            int pageNumber = (page ?? 1);


            if (idi == 1)
            {

                ViewBag.massage1 = "1";
            }
            if (idi == 0)
            {

                ViewBag.massage1 = "0";
            }
            return View(lstMessages.ToPagedList(pageNumber, pageSize));
        }

        public virtual ActionResult SendMessage(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            ViewBag.MessageBody = message.Body;
            ViewBag.MessageTitle = message.Title;
            ViewBag.MessageId = message.Id;
            var userInfos = db.UserInfos.Where(c => c.Id != message.user_id);
            return View(userInfos);

        }

        [HttpPost]
        public virtual ActionResult SendMessage(FormCollection frmCollection, string messageid)
        {
            

            int intmessageid = int.Parse(messageid);
            var message = db.Messages.Find(intmessageid);
            var chckedValues = frmCollection.GetValues("assignChkBx");

            
            if (chckedValues != null)
                foreach (var id in chckedValues)
                {
                    int userId = int.Parse(id);
                    var user = db.UserInfos.Find(userId);

                    UsersMessage usersMessage=new UsersMessage();
                    usersMessage.Message = message;
                    usersMessage.UserInfo = user;
                    usersMessage.ViewDate = DateTime.Now;
                    db.UsersMessages.Add(usersMessage);
                }
            db.SaveChanges();
            return RedirectToAction("index", routeValues: new { idi = 0 }
                );
        }


        // GET: /Message/Create
        public virtual ActionResult Create()
        {
            ViewBag.Id = db.Messages.LastOrDefault().Id;
            return View();
        }

        /*public virtual ActionResult Create(string name, Message message)
        {
             message.Body = message.Body + "<p><img src=\"~/MessageAttach/"+name+"\" /> </p>";
                return View(message);

        }*/
     
        // POST: /Message/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Create([Bind(Include = "Id,Body,Title,IsViewed,ViewDate,InsertDate,UpdateDate,IsDeleted,DeleteDate,IsActive,ActiveDeActiveDate")] Message message )
        {
            

            if (ModelState.IsValid)
            {
                UserInfo model = new UserInfo();

                model = db.UserInfos.Where(c => c.UserName == User.Identity.Name).FirstOrDefault();

                message.user_id = model.Id;
                message.Body = message.Body ;
                db.Messages.Add(message);
                db.SaveChanges();


                return RedirectToAction("Index");
            }

            return View(message);
        }

        // GET: /Message/Edit/5
        public virtual ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }




        // POST: /Message/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public virtual ActionResult Edit([Bind(Include = "Id,Body,Title,IsViewed,ViewDate,InsertDate,UpdateDate,IsDeleted,DeleteDate,IsActive,ActiveDeActiveDate")] Message message)
        {
            message.user_id = db.UserInfos.Where(c => c.UserName == User.Identity.Name).FirstOrDefault().Id;
            if (ModelState.IsValid)
            {

                db.Entry(message).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(message);
        }

        // GET: /Message/Delete/5
        public virtual ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (db.UsersMessages.Any(p => p.Message.Id == id))
            {
                return (RedirectToAction(actionName: "Index",
            routeValues: new { idi = 1 }));
            }

            Message message = db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }

        // POST: /Message/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public virtual ActionResult DeleteConfirmed(int id)
        {
            if (db.UsersMessages.Any(p => p.Message.Id ==id))
            {
                return (RedirectToAction(actionName: "Index",
            routeValues: new { idi = 0 }));
            }
            Message message = db.Messages.Find(id);
            db.Messages.Remove(message);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/PublicWebSite/Views/File/Index.cshtml
@model PublicWebSite.Models.Message
@{ Layout = null; 
   
  }

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>File Upload MVC 4</title>
    <link href="~/Addons/Content/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Addons/Content/bootstrap/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Addons/Content/jquery.fileupload.css" rel="stylesheet" />
    <script src="~/Addons/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Addons/Scripts/jquery.ui.widget.js"></script>
    <script src="~/Addons/Scripts/bootstrap.min.js"></script>
    <script src="~/Addons/Scripts/jquery.fileupload.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#fileupload').fileupload({
                dataType: 'json',
                url: '/File/UploadFiles',
                autoUpload: true,
                done: function (e, data) {
                    $('.file_name').html(data.result.name);
                    $('.file_type').html(data.result.type);
                    $('.file_size').html(data.result.size);
             
                }
            }).on('fileuploadprogressall', function (e, data) {
                var progress = parseInt(data.loaded / data.total * 100, 10);
                $('.progress .progress-bar').css('width', progress + '%');
            });
        });
    </script>
</head>
<body>

    <div class="container">
        <span class="btn btn-success fileinput-button">
            <i class="glyphicon glyphicon-plus"></i>
            <span>Add files...</span>
            <input id="fileupload" type="file" name="files[]" multiple>
        </span>
        <br />
        <div class="progress" >
            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
                <span class="sr-only">0% complete</span>
            </div>
        </div>
        <br />
        <div class="form-group ">
            @Html.EditorFor(model => model.Title, new { @class = "file_name" })
        </div>
        <br />
        <div class="file_type"></div>
        <br />
        <div class="file_size"></div>
    </div>

    @Html.ActionLink("آپلود", "create", "Message", new { name = Model.Title,message= ViewBag.message });
</body>
</html>